import { Component } from '@angular/core';
import { SharedModule } from '../../shared/shared-module';

@Component({
  selector: 'app-dashboard',
  imports: [SharedModule],
  templateUrl: './dashboard.html',
  styleUrl: './dashboard.scss',
})
export class Dashboard {
  products = [
  {
    id: 39,
    product_code: "P-0023",
    name: "MOUSE",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 110,
    selling_price: 120,
    tax_type_id: null,
    type_names: "purchasable, sellable",
    image_name: null,
    packing: "10x10'S",
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 1,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 2,
    primary_unit_name: "BOX"
  },
  {
    id: 38,
    product_code: "P-0022",
    name: "Sandip Product 1",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 100,
    selling_price: 100,
    tax_type_id: null,
    type_names: "purchasable, sellable",
    image_name: null,
    packing: null,
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 2,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 1,
    primary_unit_name: "STRIP"
  },
  {
    id: 32,
    product_code: "P-0021",
    name: "CETAMOL",
    status: true,
    remarks: "sxcdsacs",
    discount: 0,
    cost_price: 100,
    selling_price: 120,
    tax_type_id: null,
    type_names: "purchasable, sellable",
    image_name: null,
    packing: "10x10'S",
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 3,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 1,
    primary_unit_name: "STRIP"
  },
  {
    id: 31,
    product_code: "P-0020",
    name: "RAM",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 0,
    selling_price: 0,
    tax_type_id: null,
    type_names: "purchasable, sellable",
    image_name: null,
    packing: null,
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 4,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 2,
    primary_unit_name: "BOX"
  },
  {
    id: 30,
    product_code: "P-0019",
    name: "Sandip Product",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 0,
    selling_price: 0,
    tax_type_id: null,
    type_names: null,
    image_name: null,
    packing: null,
    product_type: "Inventory Item",
    types: null,
    categories: null,
    s_no: 5,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 5,
    primary_unit_name: "S Unit"
  },
  {
    id: 29,
    product_code: "P-0018",
    name: "SUMA-GAMMA",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 100,
    selling_price: 110,
    tax_type_id: null,
    type_names: "purchasable, sellable",
    image_name: null,
    packing: null,
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 6,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 1,
    primary_unit_name: "STRIP"
  },
  {
    id: 28,
    product_code: "P-0017",
    name: "SUMA-BETA",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 100,
    selling_price: 110,
    tax_type_id: null,
    type_names: "purchasable, sellable",
    image_name: null,
    packing: null,
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 7,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 1,
    primary_unit_name: "STRIP"
  },
  {
    id: 27,
    product_code: "P-0016",
    name: "SUMA-ALPHA",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 100,
    selling_price: 110,
    tax_type_id: null,
    type_names: "purchasable, sellable",
    image_name: null,
    packing: null,
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 8,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 1,
    primary_unit_name: "STRIP"
  },
  {
    id: 26,
    product_code: "P-0015",
    name: "Miyako Litche Rare ",
    status: true,
    remarks: "This is best for making fresh juice as it is in demand ",
    discount: 0,
    cost_price: 100,
    selling_price: 150,
    tax_type_id: 1,
    type_names: "purchasable, sellable",
    image_name: null,
    packing: "1 KG",
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 9,
    category_name: "FRUITS ITEMS",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: "Agriculture Product Sales Tax",
    primary_unit_id: 1,
    primary_unit_name: "STRIP"
  },
  {
    id: 25,
    product_code: "P-0014",
    name: "Miyako Banana Limited ",
    status: true,
    remarks: "This is best sessional fruit for now with quick expiry ",
    discount: 0,
    cost_price: 300,
    selling_price: 600,
    tax_type_id: null,
    type_names: "purchasable, sellable",
    image_name: "31000069_Bunch-of-bananas.jpg",
    packing: "12 DOZN",
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 10,
    category_name: "FRUITS ITEMS",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 3,
    primary_unit_name: "PCS"
  },
  {
    id: 24,
    product_code: "P-0013",
    name: "Miyako Apple Limited",
    status: true,
    remarks: "This is fresh mountain product ",
    discount: 0,
    cost_price: 200,
    selling_price: 400,
    tax_type_id: 1,
    type_names: "purchasable, sellable",
    image_name: "461000063_mustang_apple_2025.jpg",
    packing: "1 KG",
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 11,
    category_name: "FRUITS ITEMS",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: "Agriculture Product Sales Tax",
    primary_unit_id: 2,
    primary_unit_name: "BOX"
  },
  {
    id: 23,
    product_code: "P-0012",
    name: "Miyako Mango Limited ",
    status: true,
    remarks: "This item is for people who like to eat fresh, organic and pure taken from mountain of Nepal.\nLittle bit expensive .....",
    discount: 0,
    cost_price: 900,
    selling_price: 1800,
    tax_type_id: 1,
    type_names: "purchasable, sellable",
    image_name: "353000071_mustang_mango_2025.jfif",
    packing: "1 KG",
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 12,
    category_name: "FRUITS ITEMS",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: "Agriculture Product Sales Tax",
    primary_unit_id: 2,
    primary_unit_name: "BOX"
  },
  {
    id: 22,
    product_code: "P-0011",
    name: "nischal product",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 100,
    selling_price: 120,
    tax_type_id: null,
    type_names: "purchasable, sellable",
    image_name: null,
    packing: "10x10'S",
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 13,
    category_name: "GENERAL",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 1,
    primary_unit_name: "STRIP"
  },
  {
    id: 21,
    product_code: "P-0010",
    name: "stick",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 0,
    selling_price: 0,
    tax_type_id: null,
    type_names: null,
    image_name: null,
    packing: null,
    product_type: "Service Item",
    types: null,
    categories: null,
    s_no: 14,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: null,
    primary_unit_name: null
  },
  {
    id: 18,
    product_code: null,
    name: "Zenta1",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 100,
    selling_price: 110,
    tax_type_id: null,
    type_names: "purchasable, sellable",
    image_name: null,
    packing: null,
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 15,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 1,
    primary_unit_name: "STRIP"
  },
  {
    id: 17,
    product_code: null,
    name: "No Code 2",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 0,
    selling_price: 0,
    tax_type_id: null,
    type_names: null,
    image_name: null,
    packing: null,
    product_type: "Inventory Item",
    types: null,
    categories: null,
    s_no: 16,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 2,
    primary_unit_name: "BOX"
  },
  {
    id: 16,
    product_code: null,
    name: "No code",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 0,
    selling_price: 0,
    tax_type_id: null,
    type_names: "purchasable, sellable",
    image_name: null,
    packing: null,
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 17,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 2,
    primary_unit_name: "BOX"
  },
  {
    id: 15,
    product_code: "P-0009",
    name: "SERVICE 3",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 200,
    selling_price: 210,
    tax_type_id: null,
    type_names: "sellable",
    image_name: null,
    packing: null,
    product_type: "Service Item",
    types: ["sellable"],
    categories: null,
    s_no: 18,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: null,
    primary_unit_name: null
  },
  {
    id: 14,
    product_code: "P-0002",
    name: "SERVICE 2",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 100,
    selling_price: 110,
    tax_type_id: null,
    type_names: "sellable",
    image_name: null,
    packing: null,
    product_type: "Service Item",
    types: ["sellable"],
    categories: null,
    s_no: 19,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: null,
    primary_unit_name: null
  },
  {
    id: 13,
    product_code: "",
    name: "RIDEN PRODUCT",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 0,
    selling_price: 0,
    tax_type_id: null,
    type_names: "purchasable",
    image_name: null,
    packing: null,
    product_type: "Inventory Item",
    types: ["purchasable"],
    categories: null,
    s_no: 20,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 1,
    primary_unit_name: "STRIP"
  },
  {
    id: 12,
    product_code: "SER - 02",
    name: "SER - S",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 200,
    selling_price: 210,
    tax_type_id: null,
    type_names: "sellable",
    image_name: null,
    packing: null,
    product_type: "Service Item",
    types: ["sellable"],
    categories: null,
    s_no: 21,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: null,
    primary_unit_name: null
  },
  {
    id: 11,
    product_code: "SER - 01",
    name: "Canteen",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 150,
    selling_price: 160,
    tax_type_id: null,
    type_names: "purchasable, sellable",
    image_name: null,
    packing: "10x10'S",
    product_type: "Service Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 22,
    category_name: "GENERAL",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 1,
    primary_unit_name: "STRIP"
  },
  {
    id: 10,
    product_code: "Inv - 01",
    name: "INV 1",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 100,
    selling_price: 110,
    tax_type_id: null,
    type_names: "purchasable, sellable",
    image_name: null,
    packing: "10x10'S",
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 23,
    category_name: "GENERAL",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 1,
    primary_unit_name: "STRIP"
  },
  {
    id: 9,
    product_code: "P-0001",
    name: "SERVICE",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 110,
    selling_price: 120,
    tax_type_id: null,
    type_names: "purchasable, sellable",
    image_name: null,
    packing: null,
    product_type: "Service Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 24,
    category_name: "",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: null,
    primary_unit_name: null
  },
  {
    id: 7,
    product_code: "RI-003",
    name: "RID 3",
    status: true,
    remarks: null,
    discount: 0,
    cost_price: 103,
    selling_price: 105,
    tax_type_id: null,
    type_names: "purchasable, sellable",
    image_name: null,
    packing: "10x10'S",
    product_type: "Inventory Item",
    types: ["purchasable", " sellable"],
    categories: null,
    s_no: 25,
    category_name: "GENERAL",
    product_group_name: null,
    product_group_id: null,
    tax_type_name: null,
    primary_unit_id: 2,
    primary_unit_name: "BOX"
  }
];

  tableHeaders = [
    { name: 'SN', property: 'sn', sort: false },

    { name: 'Product Name', property: 'name', sortBy: 'name', sort: true },
    { name: 'Code', property: 'product_code', sortBy: 'productCode', sort: true },
    { name: 'Category', property: 'category_name', sortBy: 'productCategoriesString', sort: true },
    { name: 'Product Type', property: 'product_type', sortBy: 'productType', sort: true },
    { name: 'Primary Unit', property: 'primary_unit_name', sortBy: 'primaryUnit_name', sort: true },
    { name: 'Packing', property: 'packing', sortBy: 'packing.name', sort: true },

    { name: 'Status', property: 'status', sort: false, status: true, editStatus: false }
  ];
}
